version: '3.1'
services:
  db:
    container_name: mariadb-11.2.4-jammy
    image: mariadb:11.2.4-jammy
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: mdp
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
  adminer:
    container_name: adminer-4.8.0-standalone
    image: adminer:4.8.0-standalone
    restart: always
    ports:
      - "9080:8080"
  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      # Change the number before : to the port the web interface should be accessible on
      - '9081:80'
      # Change the number before : to the port the SMTP server should be accessible on
      - '9025:25'
volumes:
  db_data:
